dictionary = {
"abhangen von":["depend on", "Ottos Stimmung hängt stark vom Wetter ab."],
"ableiten aus": ["derive from", "Man kann das Wort 'Fenster' aus dem Lateinischen ableiten."],
"absehen von": ["refrain from", "Wenn man vom schlechten Wetter absieht, war unser Urlau schön."],
"achten auf": ["watch", "Der Busfahrer hatte nicht auf den Gegenverkehr geachtet."],
"anfangen mit": ["start with", "Jedes geschriebene deutsche Nomen fängt mit einem Großbuchstaben an."],
"antworten auf": ["answer to", "Ich habe sofort auf seinen Brief geantwortet."],
"arbeiten an": ["working on", "Die Autorin arbeitet an einem neuen Roman."],
"sich ärgern über": ["to be agry with", "Ich ärgere mih über meine Fehler."],
"aufhören mit":["finish something", "Wir hören morgen mit dem Fasten auf"],
"sich aufregen über":["get upset about something", "Reg dich nicht über Kleinigkeiten auf!"],
"ausgehen von":["come from", "Bei seiner Planung geht der Minister von einer niedrigeren Inflationstrate aus"],
"sich bedanken für":["be thankful for", "Ich habe mich bei Otto für das Geschenk bedankt"],
"sich befassen mit":["deal with something", "Wir haben uns lange mit diesem Thema befasst."],
"beginnen mit":["begin with", "Die Oper beginnt mit einer Ouverture"],
"beitragen zu":["contribute to something", "Invielen Familien müssen die Kinder zum Lebensunterhalt beitragen"],
"sich bemühen um":["strive for something", "Ich bemühe mich seit lange um ein grösseres Zimmer."],
"berichten über":["report on", "Die Zeitung berichtet über aktuelle Ereignisse"],
"beruhen auf":["be based on something", "Seine Entscheidung beruht auf einem Irrtum"],
"sich beschäftigen mit":["deal with/ busy oneself with something", "Sie beschäftigt sich mit moderner Musik"],
"sich beschränken auf":["be limited to", "Ich will nicht lange reden sondernmich auf die wichtigsten Punkte beschränken"],
"sich beschweren über":["complain", "Er beschwert sich beim Chef über seine Kollegen"],
"bestehen auf":["stand on / insist on", "Ich bestehe aufdem Umtausch der fehlerhaften Ware"],
"bestehen aus":["consist of", "Unsere Wohnung besteht aus vier Raumen"],
"bestehen in":["consist in", "Die Aufgabe des Rechnungshofes besteht in der Kontrolle der Staatsausgaben"],
"sich beteiligen an":["participate in", "An den Kosten der Party haben sich alle Gäste beteiligt."],
"sich bewerben um":["apply for", "Sie bewirbt sich um einen besseren Arbeitsplatz"],
"bitten um":["ask for", "Er hat mich um Geld gebeten"],
"danken für":["thank for", "Ich danke ihm für seine Hilfe"],
"denken an":["consider / bear in mind", "Denkst du oft an deine Heimat?"],
"diskutieren über":["discuss about", "Über Politik diskutiert Helmut gern"],
"sich eignen für":["suit someone / something", "Diese Geschichte eignet sich nicht für einen Film"],
"sich eignen zu":["qualify for sth", "Dieser Bleistift eignet sich sehr gut zum Zeichnen"],
"eindringen in":["penetrate something", "Das Regenswasser dringt in den Erdboden ein"],
"eingehen auf":["mention something", "Der Redner konnte nicht auf alle Fragen seiner Zuhörer eingehen"],
"eintreten für":["kick somebody / stand for something", "Wir treten für die Abschaffung der Todesstrafe ein"],
"einwirken auf":["affect / impact on", "Lassen Sie das Reinigungsmittel etwa zehn Minuten auf den Fleck einwirken"],
"sich entscheiden für / gegen":["choose / choose against", "Er entschied sich für die Reparatur des Hauses, also gegen den Abriss"],
"enscheiden über":["decide upon", "Eine Kommission entscheidet über die Anträge der Studenten"],
"sich entschliessen zu":["decide / determine", "Ich habe mich zur Abreise entschlossen"]
}
