dictionary  = {
"anfangen": "to begin",
"ansehen": "look at",
"arbeiten": "to work",
"argumentieren": "argument",
"aussehen": "appearence",
"bedeuten": "mean",
"beginnen": "to begin",
"bekommen": "to get",
"betreffen": "affect / conern",
"bieten": "offer",
"bilden": "shape/form",
"bleiben": "stay",
"brauchen": "need",
"bringen": "bring",
"denken": "to think",
"dürfen": "allowed",
"entstehen": "arise/develop",
"entwickeln": "develop/produce",
"ergeben": "yield/result in",
"erhalten": "receive",
"errinern": "recall",
"erkennen": "recognize",
"erklären": "explain",
"erreichen": "reach",
"erscheinen": "appear",
"erzählen": "tell",
"erwarten": "expect",
"führen": "to lead",
"geben": "to give",
"gehen": "to go",
"fahren": "to drive",
"fallen": "fall",
"fehlen": "absence/miss/lack",
"finden": "to find",
"folgen": "to follow",
"fühlen": "to feel",
"gehören": "belong",
"gelten": "be valid",
"gewinnen": "to win",
"glauben": "to believe",
"haben": "to have",
"halten": "to hold",
"helfen": "to help",
"handeln": "act/behave/trace",
"heißen": "to name",
"hören": "to hear",
"interessieren": "interest",
"kennen": "know",
"können": "can",
"kommen": "to come",
"lassen": "allowed",
"laufen": "run",
"leben": "to live",
"legen": "lay/place/put",
"lernen": "to learn",
"liegen": "lie/be/be located",
"machen": "to make",
"meinen": "mean",
"mögen": "to like",
"müssen": "must",
"nehmen": "to take",
"nennen": "call/name/mention",
"rechnen": "to count",
"reden": "to talk/speak",
"reformieren": "reform",
"riechen": "smell",
"sagen": "to say",
"schaffen": "to create/make/establish",
"scheinen": "seem to be",
"schließen": "shut down/close/conclude",
"schmezen": "pain/hurt/ache",
"schreiben": "to write",
"sehen": "to see",
"sein": "to be",
"setzen": "to set/put/place",
"sitzen": "to sit",
"sollen": "should",
"spielen": "to play",
"sprechen": "to speak",
"stehen": "to stand",
"stellen": "put/set/arrange",
"studieren": "to study",
"suchen": "to search/look for",
"tragen": "to wear/carry/bear",
"treffen": "to meet",
"tun": "to do",
"verbinden": "to connect/link/tie"
"vergleichen": "to compare/liken",
"verlieren": "to lose",
"verstehen": "to understand",
"versuchen": "to attempt",
"warten": "to wait",
"werden": "to become",
"wissen": "realize/know/be aware",
"wohnen": "live/dwell/stay",
"wollen": "to want/desire",
"zählen": "to count/score",
"zeigen": "demonstrate/show",
"ziehen": "pull"
}
